language: perl

perl:
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

notifications:
  irc:
    channels:
      - "irc.perl.org#dancer-core"
    template:
      - "%{branch}#%{build_number} by %{author}: %{message} (%{build_url})"
    on_success: change
    on_failure: always
    use_notice: true

install:
#Moo fails to install without Class::Method::Modifiers since 2012/10/19 
    - cpanm --no-skip-satisfied Class::Method::Modifiers YAML::XS
# for Pod::Weaver::Section::Consumes & ::Extends
    - mv weaver.ini _weaver.ini
    - dzil authordeps --missing | cpanm  --no-skip-satisfied || { cat ~/.cpanm/build.log ; false ; }
    - dzil listdeps --author --missing | cpanm --no-skip-satisfied || { cat ~/.cpanm/build.log ; false ; }
    - mv _weaver.ini weaver.ini

script:
    - dzil test --author --release
