language: perl

perl:
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

install:
#Moo/Role::Tiny fail to install without Class::Method::Modifiers for some reason 
    - cpanm -v Class::Method::Modifiers
    - cpanm Dist::Zilla
    - dzil authordeps --missing | cpanm || { cat ~/.cpanm/build.log ; false ; }
    - dzil listdeps --author --missing | cpanm || { cat ~/.cpanm/build.log ; false ; }
script:
    - dzil test --author --release
