#!/usr/bin/env perl
# PODNAME: dancer2
# ABSTRACT: Dancer2 command line interface

use strict;
use warnings;
use Dancer2::CLI;

Dancer2::CLI->new_with_options->run;

__END__
=pod

=head1 NAME

dancer2 - Dancer2 command line interface

=head1 SYNOPSIS

dancer2 <command> [options...]

=head1 DESCRIPTION

Dancer2 is the new generation lightweight web-framework for Perl.
This tool provides nice, easily-extendable CLI interface for it.

=head2 Documentation Index

Documentation on Dancer2 is split into several manpages. Below is a
complete outline on where to go for help.

=over 4

=item * Dancer2 Tutorial

If you are new to the Dancer approach, you should start by reading
our L<Dancer2::Tutorial>.

=item * Dancer2 Manual

L<Dancer2::Manual> is the reference for Dancer2. Here you will find
information on the concepts of Dancer2 application development and
a comprehensive reference to the Dancer2 domain specific
language.

=item * Dancer2 Keywords

The keywords for Dancer2 can be found under L<DSL Keywords|Dancer2::Manual/DSL KEYWORDS>.

=item * Dancer2 Deployment

For configuration examples of different deployment solutions involving
Dancer2 and Plack, refer to L<Dancer2::Manual::Deployment>.

=item * Dancer2 Cookbook

Specific examples of code for real-life problems and some 'tricks' for
applications in Dancer can be found in L<Dancer2::Cookbook>

=item * Dancer2 Config

For configuration file details refer to L<Dancer2::Config>. It is a
complete list of all configuration options.

=item * Dancer2 Plugins

Refer to L<Dancer2::Plugins> for a partial list of available Dancer2
plugins. Note that although we try to keep this list up to date we
expect plugin authors to tell us about new modules.

=item * Dancer2 Migration guide

L<Dancer2::Manual::Migration> provides the most up-to-date instruction on
how to convert a Dancer (1) based application to Dancer2.

=back

=head1 COMMANDS

=over

=item gen                   : create new Dancer2 application

=item version               : display version

=back

To get detailed description of each individual command run:
    dancer2 <command> --help

The lastest list of available commands can be displayed by:
    dancer2 

=head1 AUTHOR

Dancer Core Developers

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2021 by Alexis Sukrieh.

This  is  free software; you can redistribute it and/or modify it
under the same terms as the Perl 5  programming  language  system
itself.

=cut
